# Generated by Django 4.1.3 on 2022-11-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="docking_input",
            fields=[
                (
                    "title",
                    models.CharField(
                        help_text="Enter an image title",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pdb_file",
                    models.FileField(blank=True, null=True, upload_to="images/"),
                ),
                ("option1", models.IntegerField(null=True)),
                ("option2", models.IntegerField(null=True)),
                ("option3", models.IntegerField(null=True)),
                ("option4", models.IntegerField(null=True)),
            ],
        ),
    ]
